{% set name = "perses" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/perses/archive/{{ version }}.tar.gz
  sha256: a0ee50148f190adc5d01ea84cf37aa1e40dd34dfaabac36865f0b26c43b979d2

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - perses-relative = perses.app.setup_relative_calculation:run
    - perses-fah = perses.app.fah_generator:run

requirements:
  host:
    - numpy
    - pip
    - python {{ python_min }}
  run:
    - ambertools >=19.11
    - click
    - cloudpathlib-all
    - dask
    - dask-jobqueue
    - dicttoxml
    - distributed
    - fire
    - joblib
    - matplotlib-base
    - mdtraj
    - netcdf4
    - networkx >=2.0
    - numba >=0.55.2
    - numpy
    - openff-toolkit >=0.11.0
    - openff-units >=0.1.8
    - openmm >=8.0
    - openmmforcefields >=0.9.0
    - openmmtools >=0.23.0
    - openmoltools >=0.8.4
    - pandas
    - pymbar >=3.0.6,<4.0a0
    - python >={{ python_min }}
    - pyyaml
    - rich
    - scipy
    - seaborn
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - perses

about:
  home: https://github.com/choderalab/perses
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Experiments with expanded ensemble simulation to explore chemical and mutational space
  description: |
    Experiments with expanded ensemble simulation to explore chemical and mutational space
  doc_url: http://perses.readthedocs.io/
  dev_url: https://github.com/choderalab/perses

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - mikemhenry
    - ijpulidos
